#!/usr/bin/env sh
DIR="$(cd "$(dirname "$0")" && pwd)"
DATA_DIR="$DIR/data"
mkdir -p "$DATA_DIR"
curl -s https://api.warframestat.us/wfinfo/prices/ | jq . > "$DATA_DIR/prices.json"
curl -s https://api.warframestat.us/wfinfo/filtered_items/ | jq . > "$DATA_DIR/filtered_items.json"
curl -H "User-Agent: Mozilla/5.0" -H "Accept: application/json" \
     https://api.warframe.market/v2/items | \
     jq '[.data[] | {slug: .slug, name: .i18n.en.name}]' > "$DATA_DIR/items_list.json"
curl -s "https://drops.warframestat.us/data/modLocations.json" > "$DATA_DIR/modLocations.json"
curl -s "https://drops.warframestat.us/data/missionRewards.json" > "$DATA_DIR/missionRewards.json"
curl -s "https://drops.warframestat.us/data/cetusBountyRewards.json" > "$DATA_DIR/cetusBountyRewards.json"
curl -s "https://drops.warframestat.us/data/solarisBountyRewards.json" > "$DATA_DIR/solarisBountyRewards.json"
curl -s "https://drops.warframestat.us/data/zarimanRewards.json" > "$DATA_DIR/zarimanRewards.json"
curl -s "https://drops.warframestat.us/data/enemyModTables.json" > "$DATA_DIR/enemyModTables.json"
curl -s "https://drops.warframestat.us/data/transientRewards.json" > "$DATA_DIR/transientRewards.json"
curl -s "https://drops.warframestat.us/data/relics.json" > "$DATA_DIR/relics.json"
curl -s "https://raw.githubusercontent.com/WFCD/warframe-items/master/data/json/Mods.json" | jq '[.[].name]' > "$DATA_DIR/mods_all.json"
curl -s "https://raw.githubusercontent.com/WFCD/warframe-items/master/data/json/Resources.json" -o "$DATA_DIR/resources_wfcd.json"
curl -s "https://raw.githubusercontent.com/WFCD/warframe-items/master/data/json/Misc.json" -o "$DATA_DIR/misc_wfcd.json"
# Warframe public export data (used for Baro Ki'Teer item name translation)
# These only change on Warframe game updates (~every 4-8 weeks)
BROWSE_BASE="https://browse.wf/warframe-public-export-plus"
curl -s "$BROWSE_BASE/dict.en.json"           -o "$DATA_DIR/dict.en.json"
curl -s "$BROWSE_BASE/ExportUpgrades.json"    -o "$DATA_DIR/ExportUpgrades.json"
curl -s "$BROWSE_BASE/ExportWeapons.json"     -o "$DATA_DIR/ExportWeapons.json"
curl -s "$BROWSE_BASE/ExportFlavour.json"     -o "$DATA_DIR/ExportFlavour.json"
curl -s "$BROWSE_BASE/ExportResources.json"   -o "$DATA_DIR/ExportResources.json"
curl -s "$BROWSE_BASE/ExportCustoms.json"     -o "$DATA_DIR/ExportCustoms.json"
curl -s "$BROWSE_BASE/ExportBoosterPacks.json" -o "$DATA_DIR/ExportBoosterPacks.json"
curl -s "$BROWSE_BASE/ExportBundles.json"     -o "$DATA_DIR/ExportBundles.json"
curl -s "$BROWSE_BASE/ExportRelics.json"      -o "$DATA_DIR/ExportRelics.json"
/usr/bin/python3 "$DIR/scripts/data/update_prime_parts.py"
/usr/bin/python3 "$DIR/scripts/data/build_enemy_locations.py"
